# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6e2bceaa-88ae-4d00-adc6-16dc405c2b47";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0B54-3E7C";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/1a4b76db-0f6c-45b6-86df-b0e27ad1926e";
      fsType = "btrfs";
    };
  
  fileSystems."/home/lee/Data" =
    { device = "/dev/disk/by-uuid/f3b0d3f7-a9e1-46a9-a7bc-35f1643b6cd5";
      fsType = "btrfs";
      options = [ "subvol=/Data" ];
    };

  fileSystems."/home/lee/Games" =
    { device = "/dev/disk/by-uuid/f3b0d3f7-a9e1-46a9-a7bc-35f1643b6cd5";
      fsType = "btrfs";
      options = [ "subvol=/Games" ];
    };




  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
